site_name: Awesome Software Architecture
site_url: https://mehdihadeli.github.io/awesome-software-architecture/
site_description: Curated list of awesome articles and resources to learn and practice about software architecture, patterns and principles.
docs_dir: 
repo_name: mehdihadeli/awesome-software-architecture
repo_url: https://github.com/mehdihadeli/awesome-software-architecture
edit_uri: edit/master/docs/
theme: 
  name: material 
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
extra_css: [static/extra.css]
extra_javascript: [js/extra.js]
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
- Software Architecture: software-architecture.md
- Architectural Style: 
  - Architectural Style: architectural-style/architectural-style.md
  - N-Layer Architecture: architectural-style/nlayer-architecture.md
  - Clean Architecture: architectural-style/clean-architecture.md
  - Onion Architecture: architectural-style/onion-architecture.md
  - Hexagonal Architecture: architectural-style/hexagonal-architecture.md
  - Vertical Slice Architecture: architectural-style/vertical-slice-architecture.md
  - Event Driven Architecture: architectural-style/event-driven-architecture.md
  - Service Oriented Architecture: architectural-style/service-oriented-architecture.md
  - Component Based Architecture: architectural-style/component-based-architecture.md
- Architectural Design Principles: 
  - Architectural Design Principles: architectural-design-principles/architectural-design-principles.md
  - Cohesion: architectural-design-principles/cohesion.md
  - Command Query Separation - CQS: architectural-design-principles/cqs.md
  - Coupling: architectural-design-principles/coupling.md
  - Crosscutting Concerns: architectural-design-principles/crosscutting-concerns.md
  - Dependency Inversion: architectural-design-principles/dependency-inversion.md
  - Don't Repeat Yourself - DRY: architectural-design-principles/dry.md
  - Encapsulation: architectural-design-principles/encapsulation.md
  - Fail-Fast: architectural-design-principles/fail-fast.md
  - Favor Composition over Inheritance: architectural-design-principles/favor-composition-over-inheritance.md
  - GRASP: architectural-design-principles/grasp.md
  - Interface Segregation: architectural-design-principles/interface-segregation.md
  - Keep It Simple - KISS: architectural-design-principles/kiss.md
  - Open/Closed Principle: architectural-design-principles/open-closed-principle.md
  - Persistence Ignorance: architectural-design-principles/persistence-ignorance.md
  - Single Responsibility: architectural-design-principles/single-responsibility.md
  - SOLID: architectural-design-principles/solid.md
  - YAGNI: architectural-design-principles/yagni.md
- Architectural Patterns: 
  - Architectural Patterns: architectural-patterns/architectural-patterns.md
  - Domain Driven Design - Domain Centric: 
    - Domain Driven Design - Domain Centric: architectural-patterns/domain-driven-design/domain-driven-design.md
    - Aggregation: architectural-patterns/domain-driven-design/aggregation.md
    - Anemic Domain Model: architectural-patterns/domain-driven-design/anemic-domain-model.md
    - Application Service: architectural-patterns/domain-driven-design/application-service.md
    - Anti Corruption Layer: cloud-design-patterns/anti-corruption-layer-pattern.md
    - Bounded Context: architectural-patterns/domain-driven-design/bounded-context.md
    - Domain Events: architectural-patterns/domain-driven-design/domain-events.md
    - Domain Primitives: architectural-patterns/domain-driven-design/domain-primitives.md
    - Domain Service: architectural-patterns/domain-driven-design/domain-service.md
    - Enums: architectural-patterns/domain-driven-design/enums.md
    - Exception And Validation: architectural-patterns/domain-driven-design/exception-and-validation.md
    - Infrastructure: architectural-patterns/domain-driven-design/infrastructure.md
    - Mapping: architectural-patterns/domain-driven-design/mapping.md
    - Persistence Ignorance: architectural-design-principles/persistence-ignorance.md
    - Strategic Design Patterns: architectural-patterns/domain-driven-design/strategic-design-patterns.md
    - Tactical Design Patterns: architectural-patterns/domain-driven-design/tactical-design-patterns.md
    - Value Objects: architectural-patterns/domain-driven-design/value-objects.md
  - Data Driven Design - Data Centric: architectural-patterns/data-driven-design.md
  - CQRS: architectural-patterns/cqrs.md
  - Event Sourcing: architectural-patterns/event-sourcing.md
  - Microservices: 
    - Microservices: architectural-patterns/microservices/microservices.md
    - Distributed Tracing: architectural-patterns/microservices/distributed-tracing.md
    - Observibility: architectural-patterns/microservices/observibility.md)
    - Reverse Proxy:
      - Reverse Proxy: architectural-patterns/microservices/reverse-proxy/revers-proxy.md
      - YARP: architectural-patterns/microservices/reverse-proxy/yarp.md
      - Envoy: architectural-patterns/microservices/reverse-proxy/envoy.md
    - Service Discovery:
      - Service Discovery: architectural-patterns/microservices/service-discovery/service-discovery.md
      - Consul: architectural-patterns/microservices/service-discovery/consul.md
    - Tools: 
      - Tools: architectural-patterns/microservices/tools/tools.md
      - Dapr: architectural-patterns/microservices/tools/dapr.md
      - SteelToe: architectural-patterns/microservices/tools/steeltoe.md
      - Tye: architectural-patterns/microservices/tools/tye.md
  - Serverless Architectural Pattern: architectural-patterns/serverless.md
  - MicroKernel Architectural Pattern: architectural-patterns/micro-kernel.md
  - Modular Monolith: architectural-patterns/modular-monolith.md
- Design Patterns: 
  - Design Patterns: design-patterns/design-patterns.md
  - Singleton: design-patterns/singleton.md
  - Decorator Pattern: design-patterns/decorator-pattern.md
  - Specification Pattern: design-patterns/specification-pattern.md
  - Repository Pattern: design-patterns/repository-pattern.md
  - Query Object Pattern: design-patterns/query-object-pattern.md
  - Factory Pattern: design-patterns/factory-pattern.md
  - Strategy Pattern: design-patterns/strategy-pattern.md
- Cloud Design Patterns: 
  - Cloud Design Patterns: cloud-design-patterns/cloud-design-patterns.md
  - Ambassador Pattern: cloud-design-patterns/ambassador-pattern.md
  - Anti Corruption Layer Pattern: cloud-design-patterns/anti-corruption-layer-pattern.md
  - Bulkhead Pattern: cloud-design-patterns/bulkhead-pattern.md
  - Circuit Breaker Pattern: cloud-design-patterns/circuit-breaker.md
  - Exactly One Delivery: cloud-design-patterns/exactly-one-delivery.md
  - Gateway Aggregation: cloud-design-patterns/gateway-aggregation.md
  - Gateway Pattern: cloud-design-patterns/gateway-pattern.md
  - Outbox Pattern: cloud-design-patterns/outbox-pattern.md
  - Saga Pattern: cloud-design-patterns/saga.md
  - Strangler Fig Pattern: cloud-design-patterns/strangler-fig-pattern.md
- Cloud Native:
  - API Gateway: 
    - API Gateway: cloud-native/api-gateway/api-gateway.md
    - Ambassador: cloud-native/api-gateway/ambassador.md
    - Kong: cloud-native/api-gateway/kong.md
    - Ocelot: cloud-native/api-gateway/ocelot.md
  - Container Runtime: 
    - Container Runtime: cloud-native/container-runtime/container-runtime.md
    - Containerd: cloud-native/container-runtime/containerd.md
    - Cri-o: cloud-native/container-runtime/crio.md
    - Docker: 
      - Docker: cloud-native/container-runtime/docker/docker.md
      - Docker Compose: cloud-native/container-runtime/docker/docker-compose.md
  - Kubernetes: 
    - Kubernetes: cloud-native/kubernetes/kubernetes.md
    - Deployment Strategies: cloud-native/kubernetes/deployment-strategies.md
    - Deployment Tools: 
      - Argo-CD: cloud-native/kubernetes/deployment-tools/argo-cd.md
      - Helm: cloud-native/kubernetes/deployment-tools/helm.md
      - Jenkins: cloud-native/kubernetes/deployment-tools/jenkins.md
    - Ingress Controller: 
      - Ingress Controller: cloud-native/kubernetes/ingress-controller.md
      - Nginx Ingress: cloud-native/kubernetes/nginx-ingress.md
      - Traefik Ingress: cloud-native/kubernetes/traefik-ingress.md
    - Other Tools: 
      - k3s: cloud-native/kubernetes/other-tools/k3s.md
      - kind: cloud-native/kubernetes/other-tools/kind.md
      - tilt: cloud-native/kubernetes/other-tools/tilt.md
  - Load Balancing: 
    - Load Balancing: cloud-native/load-balancing/load-balancing.md
    - Fabio: cloud-native/load-balancing/fabio.md
    - MetalLB: cloud-native/load-balancing/metallb.md
    - Nginx: cloud-native/load-balancing/nginx.md
    - Traefik: cloud-native/load-balancing/traefik.md
    - Fabio: cloud-native/load-balancing/fabio.md
  - Paas Manager :
    - Paas Manager: cloud-native/paas-manager/index.md
    - Rancher: cloud-native/paas-manager/rancher.md
    - OpenShift: cloud-native/paas-manager/openshift.md
  - Reverse Proxy:
    - Reverse Proxy: cloud-native/reverse-proxy/reverse-proxy.md
    - Envoy: cloud-native/reverse-proxy/envoy.md
    - YARP: cloud-native/reverse-proxy/yarp.md
    - HAProxy: cloud-native/reverse-proxy/haproxy.md
  - Service Discovery & Registry: 
    - Service Discovery & Registry: cloud-native/service-discovery/service-discovery.md
    - Consul: cloud-native/service-discovery/consul.md
    - Eureka: cloud-native/service-discovery/eureka.md
  - Service Mesh: 
    - Service Mesh: cloud-native/service-mesh/service-mesh.md
    - Istio: cloud-native/service-mesh/istio.md
    - Consul-Connect: cloud-native/service-mesh/consul-connect.md
    - Maesh: cloud-native/service-mesh/maesh.md
    - Linkerd: cloud-native/service-mesh/linkerd.md
- Object Oriented Design: object-oriented-design.md
- Distributed Systems Design: distributed-systems-design.md
- Scalable Software Architecture: scalable-software-architecture.md
- Clean Code: clean-code.md
- Design Best Practices: 
  - Design Best Practices: design-best-practices/design-best-practices.md
  - 12 Factor: design-best-practices/12-factor.md
  - Strongly Type Ids: design-best-practices/strongly-type-ids.md
  - Thin Controllers: design-best-practices/thin-controllers.md
- Anti Patterns: 
  - Anti Patterns: anti-patterns/anti-patterns.md
  - Anemic Domain Model: architectural-patterns/domain-driven-design/anemic-domain-model.md)
  - Big Ball of Mud: anti-patterns/big-ball-of-mud.md
  - Code Smells: anti-patterns/code-smells.md
  - Partial/Optional Object: anti-patterns/partial-object.md
  - Static Cling: anti-patterns/static-cling.md
- Eventual Consistency: eventual-consistency.md
- Messaging Patterns:
  - Messaging Patterns: messaging/messaging.md
  - Kafka: messaging/kafka.md
  - RabbitMQ: messaging/rabbitmq.md
  - Azure Service Bus: azure/azure-service-bus.md
  - NATS: messaging/nats.md
- Distributed Transactions: distributed-transactions.md
- Concurrency: concurrency.md
- Eventual Consistency: eventual-consistency.md
- RESTful API Design: rest.md
- Caching: caching.md
- Aspect Oriented Programming: aop.md
- Packaging: packaging.md
- Refactoring: refactoring.md
- Azure Application Architecture: 
  - Azure Application Architecture: azure/azure-application-architecture.md
  - Azure Active Directory: azure/azure-active-directory.md
  - Azure Functions: azure/azure-functions.md
  - Azure Service Bus: azure/azure-service-bus.md
  - Azure Template: azure/azure-template.md
  - Azure Identity: azure/azure-identity.md
- Modeling: 
  - Modeling: modeling/modeling.md
  - Architecture Diagram: modeling/architecture-diagram.md
  - Class Diagram: modeling/class-diagram.md
  - Component Diagram: modeling/component-diagram.md
  - Conceptual Diagram: modeling/conceptual-diagram.md
  - Conceptual Modeling: modeling/conceptual-modeling.md
  - Data Modeling Notations: modeling/data-modeling-notations.md
  - ER Diagrams: modeling/er-diagrams.md
  - Logical Modeling: modeling/logical-modeling.md
  - Physical Modeling: modeling/physical-modeling.md
  - Relationship: modeling/relationship.md
  - Tools: modeling/tools.md
  - Use Case Diagram: modeling/use-case-diagram.md
- Event Storming: event-storming.md
- Engineering Blogs: engineering-blogs.md
- Others: others.md


copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
