site_name: Awesome Software Architecture
site_url: https://mehdihadeli.github.io/awesome-software-architecture/
site_description: Curated list of awesome articles and resources to learn and practice about software architecture, patterns and principles.
docs_dir: docs/
repo_name: 'GitHub'
repo_url: https://github.com/mehdihadeli/awesome-software-architecture
theme: 
  name: material 
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
extra_css:
  - static/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
      #baselevel: 2

nav:
- Software Architecture: docs/software-architecture.md
- Architectural Style: 
  - Architectural Style: docs/architectural-style.md
  - Traditional N-Layer Architecture: docs/architectural-style/nlayer-architecture.md
  - Clean Architecture: docs/architectural-style/clean-architecture.md
  - Onion Architecture: docs/architectural-style/onion-architecture.md
  - Ports And Adapters Architecture (Hexagonal Architecture): docs/architectural-style/hexagonal-architecture.md
  - Vertical Slice Architecture: docs/architectural-style/vertical-slice-architecture.md
  - Event Driven Architecture: docs/architectural-style/event-driven-architecture.md
  - Service Oriented Architecture: docs/architectural-style/service-oriented-architecture.md
  - Component Based Architecture: docs/architectural-style/component-based-architecture.md
- Architectural Design Principles: 
  - Architectural Design Principles: docs/architectural-design-principles.md
  - Crosscutting Concerns: docs/architectural-design-principles/crosscutting-concerns.md
  - Encapsulation: docs/architectural-design-principles/encapsulation.md
  - Dependency Inversion: docs/architectural-design-principles/dependency-inversion.md
  - Interface Segregation Principle: docs/architectural-design-principles/interface-segregation-principle.md
  - Single Responsibility: docs/architectural-design-principles/single-responsibility-principle.md
  - Open/Closed Principle: docs/architectural-design-principles/open-closed-principle.md
  - Command Query Separation: docs/architectural-design-principles/cqs.md
  - Favor Composition over Inheritance: docs/architectural-design-principles/favor-composition-over-inheritance.md
  - DRY: docs/architectural-design-principles/dry.md
  - KISS: docs/architectural-design-principles/kiss.md
  - YAGNI: docs/architectural-design-principles/yagni.md
  - Minimize Coupling: docs/architectural-design-principles/minimize-coupling.md
  - Maximize Cohesion: docs/architectural-design-principles/maximize-cohesion.md
  - Persistence Ignorance: docs/architectural-design-principles/persistence-ignorance.md
  - GRASP: docs/architectural-design-principles/grasp.md
- Architectural Patterns: 
  - Architectural Patterns: docs/architectural-patterns.md
  - Domain Driven Design - Domain Centric: 
    - Domain Driven Design - Domain Centric: docs/architectural-patterns/domain-driven-design/domain-driven-design.md
    - Aggregation: docs/architectural-patterns/domain-driven-design/aggregation.md
    - Anemic Domain Model: docs/architectural-patterns/domain-driven-design/anemic-domain-model.md
    - Application Service: docs/architectural-patterns/domain-driven-design/application-service.md
    - Bounded Context: docs/architectural-patterns/domain-driven-design/bounded-context.md
    - Domain Events: docs/architectural-patterns/domain-driven-design/domain-events.md
    - Domain Primitives: docs/architectural-patterns/domain-driven-design/domain-primitives.md
    - Domain Service: docs/architectural-patterns/domain-driven-design/domain-service.md
    - Enums: docs/architectural-patterns/domain-driven-design/enums.md
    - Exception And Validation: docs/architectural-patterns/domain-driven-design/exception-and-validation.md
    - Infrastructure: docs/architectural-patterns/domain-driven-design/infrastructure.md
    - Mapping: docs/architectural-patterns/domain-driven-design/mapping.md
    - Strategic Design Patterns: docs/architectural-patterns/domain-driven-design/strategic-design-patterns.md
    - Tactical Design Patterns: docs/architectural-patterns/domain-driven-design/tactical-design-patterns.md
    - Value Objects: docs/architectural-patterns/domain-driven-design/value-objects.md
  - Data Driven Design - Data Centric: docs/architectural-patterns/data-driven-design.md
  - CQRS: docs/architectural-patterns/cqrs.md
  - Event Sourcing: docs/architectural-patterns/event-sourcing.md
  - Microservices: 
    - Microservices: docs/architectural-patterns/microservices/microservices.md
    - Reverse Proxy:
      - Reverse Proxy: docs/architectural-patterns/microservices/reverse-proxy/revers-proxy.md
      - YARP: docs/architectural-patterns/microservices/reverse-proxy/yarp.md
    - Service Discovery:
      - Service Discovery: docs/architectural-patterns/microservices/service-discovery/service-discovery.md
      - Consul: docs/architectural-patterns/microservices/service-discovery/consul.md
    - Tools: 
      - Tools: docs/architectural-patterns/microservices/tools/tools.md
      - Dapr: docs/architectural-patterns/microservices/tools/dapr.md
      - SteelToe: docs/architectural-patterns/microservices/tools/steeltoe.md
      - Tye: docs/architectural-patterns/microservices/tools/tye.md
  - Serverless Architectural Pattern: docs/architectural-patterns/serverless.md
  - MicroKernel Architectural Pattern: docs/architectural-patterns/micro-kernel.md
  - Modular Monolith: docs/architectural-patterns/modular-monolith.md
- Design Patterns: 
  - Design Patterns: docs/design-patterns/design-patterns.md
  - Singleton: docs/design-patterns/singleton.md
  - Decorator Pattern: docs/design-patterns/decorator-pattern.md
  - Specification Pattern: docs/design-patterns/specification-pattern.md
  - Repository Pattern: docs/design-patterns/repository-pattern.md
  - Query Object Pattern: docs/design-patterns/query-object-pattern.md
  - Factory Pattern: docs/design-patterns/factory-pattern.md
  - Strategy Pattern: docs/design-patterns/strategy-pattern.md
- Cloud Design Patterns: 
  - Cloud Design Patterns: docs/cloud-design-patterns/cloud-design-patterns.md
  - Ambassador Pattern: docs/cloud-design-patterns/ambassador-pattern.md
  - Anti Corruption Layer Pattern: docs/cloud-design-patterns/anti-corruption-layer-pattern.md
  - Bulkhead Pattern: docs/cloud-design-patterns/bulkhead-pattern.md
  - Circuit Breaker Pattern: docs/cloud-design-patterns/circuit-breaker.md
  - Exactly One Delivery: docs/cloud-design-patterns/exactly-one-delivery.md
  - Gateway Aggregation: docs/cloud-design-patterns/gateway-aggregation.md
  - Gateway Pattern: docs/cloud-design-patterns/gateway-pattern.md
  - Outbox Pattern: docs/cloud-design-patterns/outbox-pattern.md
  - Saga Pattern: docs/cloud-design-patterns/saga.md
  - Strangler Fig Pattern: docs/cloud-design-patterns/strangler-fig-pattern.md
- Object Oriented Design: docs/object-oriented-design.md
- Distributed Systems Design: docs/distributed-systems-design.md
- Scalable Software Architecture: docs/scalable-software-architecture.md
- Clean Code: docs/clean-code.md
- Design Best Practices: 
  - Design Best Practices: docs/design-best-practices/design-best-practices.md
  - 12 Factor: docs/design-best-practices/12-factor.md
  - Strongly Type Ids: docs/design-best-practices/strongly-type-ids.md
  - Thin Controllers: docs/design-best-practices/thin-controllers.md
- Anti Patterns: 
  - Anti Patterns: docs/anti-patterns/anti-patterns.md
  - Code Smells: docs/anti-patterns/code-smells.md
- Eventual Consistency: docs/eventual-consistency.md
- Messaging Patterns:
  - Messaging Patterns: docs/messaging/messaging.md
  - Kafka: docs/messaging/kafka.md
  - RabbitMQ: docs/messaging/rabbitmq.md
- Distributed Transactions: docs/distributed-transactions.md
- Concurrency: docs/concurrency.md
- Eventual Consistency: docs/eventual-consistency.md
- RESTful API Design: docs/rest.md
- Caching: docs/caching.md
- Packaging: docs/packaging.md
- Refactoring: docs/refactoring.md
- Azure Application Architecture: 
  - Azure Application Architecture: docs/azure/azure-application-architecture.md
  - Azure Active Directory: docs/azure/azure-active-directory.md
  - Azure Functions: docs/azure/azure-functions.md
  - Azure Service Bus: docs/azure/azure-service-bus.md
  - Azure Template: docs/azure/azure-template.md
  - Azure Identity: docs/azure/azure-identity.md
- Modeling: 
  - Modeling: docs/modeling/modeling.md
  - Class Diagram: docs/modeling/class-diagram.md
  - Component Diagram: docs/modeling/component-diagram.md
  - Conceptual Diagram: docs/modeling/conceptual-diagram.md
  - Conceptual Modeling: docs/modeling/conceptual-modeling.md
  - Data Modeling Notations: docs/modeling/data-modeling-notations.md
  - ER Diagrams: docs/modeling/er-diagrams.md
  - Logical Modeling: docs/modeling/logical-modeling.md
  - Physical Modeling: docs/modeling/physical-modeling.md
  - Relationship: docs/modeling/relationship.md
  - Tools: docs/modeling/tools.md
  - Use Case Diagram: docs/modeling/use-case-diagram.md
- Event Storming: docs/event-storming.md
- Engineering Blogs: docs/engineering-blogs.md
- Other: docs/other.md


copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli